local tinsert = table.insert
local inserted = false

function DBMCPHotSRu()
    if inserted then return end
    tinsert(DBM.Counts, { text = "HoTS: Абатур",                value = "HoTS_Abathur",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Abathur\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Адъютант",              value = "HoTS_Adjutant",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Adjutant\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Аларак",                value = "HoTS_Alarak",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Alarak\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Алекстраза",            value = "HoTS_Alexstrasza",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Alexstrasza\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Андуин",                value = "HoTS_Anduin",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Anduin\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Иларий",                value = "HoTS_Angel",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Angel\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Ануб'арак",             value = "HoTS_Anubarak",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Anubarak\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Арена",                 value = "HoTS_Arena",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Arena\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Артас",                 value = "HoTS_Arthas",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Arthas\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Афина",                 value = "HoTS_Athena",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Athena\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Соня",                  value = "HoTS_Barbarian",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Barbarian\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Черносерд",             value = "HoTS_Blackheart",   path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Blackheart\\",   max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Блэйз",                 value = "HoTS_Blaze",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Blaze\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Светик",                value = "HoTS_Brightwing",   path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Brightwing\\",   max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Командор",              value = "HoTS_Commodore",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Commodore\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Джоанна",               value = "HoTS_Crusader",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Crusader\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Смертокрыл",            value = "HoTS_Deathwing",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Deathwing\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Декард",                value = "HoTS_Deckard",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Deckard\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Стандартный",           value = "HoTS_Default",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Default\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Белет",                 value = "HoTS_Demon",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Demon\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Валла",                 value = "HoTS_DemonHunter",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\DemonHunter\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Диабло",                value = "HoTS_Diablo",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Diablo\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Дрек'Тар",              value = "HoTS_DrekThar",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\DrekThar\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: D.Va",                  value = "HoTS_DVa",          path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\DVa\\",          max = 5})
    tinsert(DBM.Counts, { text = "HoTS: E.T.C.",                value = "HoTS_ETC",          path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\ETC\\",          max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Фалстад",               value = "HoTS_Falstad",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Falstad\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Феникс",                value = "HoTS_Fenix",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Fenix\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Королева Белладонна",   value = "HoTS_GardensDay",   path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\GardensDay\\",   max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Гаррош",                value = "HoTS_Garrosh",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Garrosh\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Газлоу",                value = "HoTS_Gazlowe",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Gazlowe\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Гэндзи",                value = "HoTS_Genji",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Genji\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Хандзо",                value = "HoTS_Hanzo",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Hanzo\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Дробитель",             value = "HoTS_Hogger",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Hogger\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Иллидан",               value = "HoTS_Illidan",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Illidan\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Империй",               value = "HoTS_Imperius",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Imperius\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Джайна",                value = "HoTS_Jaina",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Jaina\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Крысавчик",             value = "HoTS_Junkrat",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Junkrat\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Кел'Тузад",             value = "HoTS_Kelthuzad",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Kelthuzad\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Королева шипов",        value = "HoTS_LadyofThorns", path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\LadyofThorns\\", max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Ли Ли",                 value = "HoTS_LiLi",         path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\LiLi\\",         max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Майев",                 value = "HoTS_Maiev",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Maiev\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Малфурион",             value = "HoTS_Malfurion",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Malfurion\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мал'Ганис",             value = "HoTS_MalGanis",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\MalGanis\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мэй",                   value = "HoTS_Mei",          path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Mei\\",          max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мефисто",               value = "HoTS_Mephisto",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Mephisto\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мира Хан",              value = "HoTS_Mira",         path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Mira\\",         max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мурадин",               value = "HoTS_Muradin",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Muradin\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Могильщик",             value = "HoTS_Necromancer",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Necromancer\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Кахира",                value = "HoTS_NexusHunter",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\NexusHunter\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Орфея",                 value = "HoTS_Orphea",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Orphea\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Повелитель воронов",    value = "HoTS_RavenLord",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\RavenLord\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Регар",                 value = "HoTS_Rehgar",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Rehgar\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Сержант Кувалда",       value = "HoTS_SiegeTank",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\SiegeTank\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Ка",                    value = "HoTS_SnakeGod",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\SnakeGod\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Неитис",                value = "HoTS_SpiderQueen",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\SpiderQueen\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Стежок",                value = "HoTS_Stitches",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Stitches\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Тассадар",              value = "HoTS_Tassadar",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Tassadar\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Мальчишка комментатор", value = "HoTS_Toy18",        path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Toy18\\",        max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Тайкус",                value = "HoTS_Tychus",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Tychus\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Тираэль",               value = "HoTS_Tyrael",       path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Tyrael\\",       max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Меха Тираэль",          value = "HoTS_TyraelMecha",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\TyraelMecha\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Вандар",                value = "HoTS_Vanndar",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Vanndar\\",      max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Вольская",              value = "HoTS_Volskaya",     path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Volskaya\\",     max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Вайтмейн",              value = "HoTS_Whitemane",    path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Whitemane\\",    max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Назибо",                value = "HoTS_WitchDoctor",  path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\WitchDoctor\\",  max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Ирель",                 value = "HoTS_Yrel",         path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Yrel\\",         max = 5})
    tinsert(DBM.Counts, { text = "HoTS: Зератул",               value = "HoTS_Zeratul",      path = "Interface\\AddOns\\DBM-CountPack-HoTS-RU\\Zeratul\\",      max = 5})
    inserted = true
end
